import os
import subprocess
import logging

logger = logging.getLogger(__name__)

DDOS_CONF_PATH = "/etc/nginx/conf.d/waf_ddos.conf"
HARDENING_CONF_PATH = "/etc/nginx/conf.d/waf_hardening.conf"


def apply_ddos_settings(settings: dict) -> bool:
    """
    Generates NGINX rate-limiting configuration based on the provided settings
    and reloads NGINX to apply them.
    """
    try:
        rate_limit_rps = settings.get("rate_limit_rps", 50)
        burst_tolerance = settings.get("burst_tolerance", 100)
        trusted_ips = settings.get("trusted_ips", [])
        bot_action = settings.get("bot_mitigation_action", "Silent Drop")
        advanced_rules = settings.get("advanced_rules", [])

        # Determine HTTP status code based on bot_action
        # Silent Drop -> 444 (NGINX special code to close connection)
        # Block -> 429 (Too Many Requests) or 503 (Service Unavailable)
        status_code = 444 if bot_action == "Silent Drop" else 429

        config_lines = [
            "# Auto-generated by CyberSentinel WAF GUI",
            "# Do not edit manually",
            "",
        ]

        # Define GeoIP2 databases if they exist on disk
        COUNTRY_DB = "/opt/ModSecurity/WAF_GUI/backend/app/data/GeoLite2-Country.mmdb"
        ASN_DB = "/opt/ModSecurity/WAF_GUI/backend/app/data/GeoLite2-ASN.mmdb"

        has_country_db = os.path.exists(COUNTRY_DB)
        has_asn_db = os.path.exists(ASN_DB)

        if has_country_db:
            config_lines.append(f"geoip2 {COUNTRY_DB} {{")
            config_lines.append(
                "    $geoip2_data_country_code source=$remote_addr country iso_code;"
            )
            config_lines.append("}")
            config_lines.append("")

        if has_asn_db:
            config_lines.append(f"geoip2 {ASN_DB} {{")
            config_lines.append(
                "    $geoip2_data_asn source=$remote_addr autonomous_system_number;"
            )
            config_lines.append(
                "    $geoip2_data_org source=$remote_addr autonomous_system_organization;"
            )
            config_lines.append("}")
            config_lines.append("")

        # We always define the $limit_key variable.
        # If trusted_ips exist, it is dynamic. If not, it is equivalent to $binary_remote_addr.
        if trusted_ips:
            config_lines.append("geo $limit {")
            config_lines.append("    default 1;")
            for ip in trusted_ips:
                if ip.strip():
                    config_lines.append(f"    {ip.strip()} 0;")
            config_lines.append("}")
            config_lines.append("")
            config_lines.append("map $limit $limit_key {")
            config_lines.append('    0 "";')
            config_lines.append("    1 $binary_remote_addr;")
            config_lines.append("}")
        else:
            config_lines.append("map $host $limit_key {")
            config_lines.append("    default $binary_remote_addr;")
            config_lines.append("}")

        config_lines.append("")
        zone_key = "$limit_key"

        config_lines.append(
            f"limit_req_zone {zone_key} zone=waf_ddos_req:10m rate={rate_limit_rps}r/s;"
        )
        config_lines.append(f"limit_req_status {status_code};")
        config_lines.append("")
        # Apply globally to all traffic in the HTTP context
        config_lines.append(
            f"limit_req zone=waf_ddos_req burst={burst_tolerance} nodelay;"
        )

        # Connection limiting
        config_lines.append(f"limit_conn_zone {zone_key} zone=waf_ddos_conn:10m;")
        config_lines.append(f"limit_conn_status {status_code};")
        config_lines.append(
            "limit_conn waf_ddos_conn 100;"
        )  # Hardcoded max 100 connections per IP for now
        config_lines.append("")

        # --- Advanced Rate Limiting Rules ---
        if advanced_rules:
            config_lines.append("# --- Advanced Rate Limiting Rules ---")
            for rule in advanced_rules:
                if not rule.get("enabled", True):
                    continue
                rule_id = rule.get("id")
                rule_name = rule.get("name", f"Rule {rule_id}")
                param_type = rule.get("parameter_type", "URI")
                param_value = rule.get("parameter_value", "")
                rule_rps = rule.get("rate_limit_rps", 10)
                rule_burst = rule.get("burst_tolerance", 20)

                # Determine NGINX variable to inspect
                nginx_var = "$request_uri"
                if param_type == "URI":
                    nginx_var = "$request_uri"
                elif param_type == "Method":
                    nginx_var = "$request_method"
                elif param_type == "Referrer":
                    nginx_var = "$http_referer"
                elif param_type == "Content-Type":
                    nginx_var = "$http_content_type"
                elif param_type == "IP":
                    nginx_var = "$remote_addr"
                elif param_type == "Country":
                    if not has_country_db:
                        logger.warning(
                            f"Skipping Country rate limiting rule '{rule_name}' because Country GeoIP DB is missing."
                        )
                        continue
                    nginx_var = "$geoip2_data_country_code"
                elif param_type == "ISP/ASN":
                    if not has_asn_db:
                        logger.warning(
                            f"Skipping ISP/ASN rate limiting rule '{rule_name}' because ASN GeoIP DB is missing."
                        )
                        continue
                    # Match ASN (if numeric) or Org name
                    if param_value.strip().isdigit():
                        nginx_var = "$geoip2_data_asn"
                    else:
                        nginx_var = "$geoip2_data_org"
                elif param_type == "Header":
                    # Custom header parsing (e.g. "X-API-Key: value" or just "X-API-Key")
                    if ":" in param_value:
                        parts = param_value.split(":", 1)
                        header_name = parts[0].strip()
                        param_value = parts[1].strip()
                    else:
                        header_name = param_value.strip()
                        param_value = ".*"  # Match anything if no pattern is specified

                    nginx_var = "$http_" + header_name.lower().replace("-", "_")

                # Escape double quotes inside the parameter value to avoid NGINX parse errors
                clean_value = param_value.replace('"', '\\"')

                config_lines.append(
                    f"# Rule: {rule_name} (Type: {param_type}, Match: {param_value})"
                )
                config_lines.append(f"map {nginx_var} $limit_key_{rule_id} {{")
                # Map to $limit_key (so trusted IPs automatically bypass this check)
                config_lines.append(f'    "~*{clean_value}" {zone_key};')
                config_lines.append('    default "";')
                config_lines.append("}")
                config_lines.append(
                    f"limit_req_zone $limit_key_{rule_id} zone=zone_{rule_id}:10m rate={rule_rps}r/s;"
                )
                config_lines.append(
                    f"limit_req zone=zone_{rule_id} burst={rule_burst} nodelay;"
                )
                config_lines.append("")

        config_content = "\n".join(config_lines) + "\n"

        # Since the backend runs as root (via sudo), it can write directly
        with open(DDOS_CONF_PATH, "w", encoding="utf-8") as f:
            f.write(config_content)

        logger.info(f"Successfully generated NGINX DDoS config at {DDOS_CONF_PATH}")

        # Reload NGINX to apply
        return reload_nginx()

    except Exception as e:
        logger.error(f"Failed to apply DDoS settings: {e}")
        return False


def reload_nginx() -> bool:
    """Reloads the NGINX service."""
    try:
        result = subprocess.run(
            ["nginx", "-s", "reload"], capture_output=True, text=True
        )
        if result.returncode == 0:
            logger.info("NGINX reloaded successfully.")
            return True
        else:
            logger.error(f"NGINX reload failed: {result.stderr}")
            return False
    except Exception as e:
        logger.error(f"Error reloading NGINX: {e}")
        return False


def disable_ddos_mitigation() -> bool:
    """Removes the DDoS configuration and reloads NGINX."""
    try:
        if os.path.exists(DDOS_CONF_PATH):
            os.remove(DDOS_CONF_PATH)
            logger.info(f"Removed {DDOS_CONF_PATH}")
            return reload_nginx()
        return True
    except Exception as e:
        logger.error(f"Failed to disable DDoS mitigation: {e}")
        return False


def apply_hardening_settings(settings: dict) -> bool:
    """
    Generates NGINX hardening and IP ACL configuration based on the provided settings
    and reloads NGINX to apply them.
    """
    try:
        server_cloaking = settings.get("server_cloaking", True)
        ip_blacklist = settings.get("ip_blacklist", [])
        ip_whitelist = settings.get("ip_whitelist", [])

        config_lines = [
            "# Auto-generated by CyberSentinel WAF GUI",
            "# Do not edit manually",
            "",
        ]

        if server_cloaking:
            config_lines.append("server_tokens off;")
        else:
            config_lines.append("server_tokens on;")

        config_lines.append("")

        # 1. Write Whitelist allow directives
        if ip_whitelist:
            config_lines.append("# IP Whitelist Rules")
            for ip in ip_whitelist:
                if ip.strip():
                    config_lines.append(f"allow {ip.strip()};")
            config_lines.append("")

        # 2. Write Blacklist deny directives
        if ip_blacklist:
            config_lines.append("# IP Blacklist Rules")
            for ip in ip_blacklist:
                if ip.strip():
                    config_lines.append(f"deny {ip.strip()};")
            config_lines.append("")

        config_content = "\n".join(config_lines) + "\n"

        with open(HARDENING_CONF_PATH, "w", encoding="utf-8") as f:
            f.write(config_content)

        logger.info(
            f"Successfully generated NGINX hardening config at {HARDENING_CONF_PATH}"
        )
        return reload_nginx()
    except Exception as e:
        logger.error(f"Failed to apply hardening settings: {e}")
        return False


def disable_hardening() -> bool:
    """Removes the hardening configuration and reloads NGINX."""
    try:
        if os.path.exists(HARDENING_CONF_PATH):
            os.remove(HARDENING_CONF_PATH)
            logger.info(f"Removed {HARDENING_CONF_PATH}")
            return reload_nginx()
        return True
    except Exception as e:
        logger.error(f"Failed to disable hardening: {e}")
        return False
