/var/log/modsec_audit.log {
	weekly
	missingok
	rotate 9
	compress
	delaycompress
	notifempty
	create 0644 www-data www-data
	sharedscripts
	postrotate
		systemctl kill -s USR1 openresty.service >/dev/null 2>&1 || true
	endscript
}
